name: flutter_guide
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  auto_route: ^8.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
